### ISSUE TITLE
 Something went wrong when extracting the files from the repostory tar file.

### ISSUE THREAD

**Issue by leninMoscoso** [prisma/try-prisma#25]
show this mistake when I try to use it on Windows.
![Captura de pantalla 2022-11-28 163008](https://user-images.githubusercontent.com/65478491/204387121-be818a1f-5423-488c-8b22-19a3e9e4bb4d.png)

**Comment by geojimas** [comment]
same here

**Comment by sabinadams** [comment]
Thanks for posting this issue! This is definitely isolated to Windows machines.
