### ISSUE TITLE
Try Molt Command instead of commander?

### ISSUE THREAD

**Issue by jasonkuhrt** [prisma/try-prisma#27]
Hey @sabinadams!

If you're up for it I'd love for this project to use https://github.com/jasonkuhrt/molt/tree/main/packages/@molt/command. I suspect there will be some rough edges that I'd be happy to address with your feedback. If it isn't overwhelming better than commander that's also useful to know so I can improve Molt.

No pressure just a thought! Cheers :)

**Comment by sabinadams** [comment]
I'll certainly give it a look! That part of try-prisma is actually pretty simple so I'm sure it could slot in pretty easily. 

I'm glad you reminded me actually. After I'd already written the tool, I found your package and wanted to give it a try.
